### PR TITLE
bump cardano-node (v8.10.0-pre), db-sync (vsancho-4.2.1), csl (12.0.0-alpha.29)

### PR DESCRIPTION
**Pull request by MSzalowski**
## List of changes

bump:
* cardano-node - v8.10.0-pre
* db-sync - vsancho-4.2.1
* csl - v12.0.0-alpha.29

### CODE REVIEW

**Review by Ryun1 — APPROVED** [review]
Lets do it!

**Comment by placek** [comment]
This has no sense at all…

The deployment configuration on branch `main` is heavily outdated and to perform any deploy on beta someone (i.e. I) has to:
* build images from that branch semi-manually, since there is no Makefile configuration for subsequent modules,
* use the newest deployment configuration to perform generation of all required target config that ends up on target machine,
* exclude the metadata-validate service from the stack since there is no such thing on that branch,
* do the respin, hoping that the following deploy will actualy bring up the services…

Aftermatch of this ridiculus take will be:
* backend not suitable for new sanchonet after respin,
* backend not adjusted to new DBSync schema,
* lack of metadata-validate service,
* many other problems that I am not aware of.

**Comment by Ryun1** [comment]
Revert? https://github.com/IntersectMBO/govtool/pull/831

**Comment by MSzalowski** [comment]
Yep, let's revert that

**Comment by MSzalowski** [comment]
> backend not suitable for new sanchonet after respin
> backend not adjusted to new DBSync schema,

Only proposals has changed but it doesn't impact the frontend on current beta, as on frontend the proposals are displayed as they are.

> lack of metadata-validate service

Not needed.

The only problem I can see Is only the deployment configuration that has changed and true - building it from source might not be done easily, but is it possible to push the current deployment config to main with the bumped cardano node and db-sync?

@placek

**Comment by placek** [comment]
> Only proposals have changed.

I am not sure about that since I recall some issues you guys reported recently, after the node+dbsync had been respun. I would like to test such a version somehow before releasing it to the world.

> Is it possible to push the current deployment config to the main with the bumped Cardano node and db-sync?

It is not as simple as it seems: all the changes for the deployment and infra configuration have to be cherry-picked here to introduce a fully operational deployment with no surprises. Now it is imposible to perform a deploy without importing the deployment configuration manually from other branch.

This also involves the introduction of the metadata-validate service since it is a part of the stack, and recent changes, fixing #742, incorporate this module in many places in the configuration.

I do not want to end up with a situation where we have separate setups for development and main - there will be no one willing to maintain such unnecessary complexity.

**Pull request merged**
